wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
anneal_clr_by_factor:
  desc: null
  value: 1.0
backward_iters:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 64
budget:
  desc: null
  value: 0.0
clip_obs:
  desc: null
  value: 20
clip_range:
  desc: null
  value: 0.2
clip_range_cost_vf:
  desc: null
  value: null
clip_range_reward_vf:
  desc: null
  value: null
cn_acs_select_dim:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
cn_batch_size:
  desc: null
  value: null
cn_eps:
  desc: null
  value: 1.0e-05
cn_layers:
  desc: null
  value:
  - 20
cn_learning_rate:
  desc: null
  value: 0.01
cn_normalize:
  desc: null
  value: false
cn_obs_select_dim:
  desc: null
  value:
  - 2
  - 3
  - 4
  - 5
  - 6
cn_plot_every:
  desc: null
  value: 1
cn_reg_coeff:
  desc: null
  value: 0
cn_target_kl_new_old:
  desc: null
  value: 10
cn_target_kl_old_new:
  desc: null
  value: 10
config_file:
  desc: null
  value: config_icrl_logic_jtl.json
cost_gae_lambda:
  desc: null
  value: 0.95
cost_gamma:
  desc: null
  value: 0.99
cost_info_str:
  desc: null
  value: cost
cost_vf_coef:
  desc: null
  value: 0.5
cost_vf_layers:
  desc: null
  value:
  - 64
  - 64
derivative_control_coeff:
  desc: null
  value: 0
derivative_cost_ema_alpha:
  desc: null
  value: 0.5
deterministic:
  desc: null
  value: true
device:
  desc: null
  value: cpu
dont_normalize_cost:
  desc: null
  value: false
dont_normalize_obs:
  desc: null
  value: false
dont_normalize_reward:
  desc: null
  value: false
ent_coef:
  desc: null
  value: 0.0
eval_env_id:
  desc: null
  value: CJTL-v0
eval_every:
  desc: null
  value: 2048
expert_path:
  desc: null
  value: icrl/expert_data/JTL
expert_rollouts:
  desc: null
  value: 20
file_to_run:
  desc: null
  value: icrl
forward_timesteps:
  desc: null
  value: 50000
group:
  desc: null
  value: null
integral_control_coeff:
  desc: null
  value: 0.0001
learning_rate:
  desc: null
  value: 0.0003
max_grad_norm:
  desc: null
  value: 0.5
n_epochs:
  desc: null
  value: 10
n_iters:
  desc: null
  value: 20
n_steps:
  desc: null
  value: 2048
name:
  desc: null
  value: JTL-v0_CJTL-v0_s_83_sid_-1
no_importance_sampling:
  desc: null
  value: false
num_threads:
  desc: null
  value: 5
penalty_initial_value:
  desc: null
  value: 1
penalty_learning_rate:
  desc: null
  value: 0.1
per_step_importance_sampling:
  desc: null
  value: false
pid_delay:
  desc: null
  value: 1
policy_layers:
  desc: null
  value:
  - 64
  - 64
policy_name:
  desc: null
  value: TwoCriticsMlpPolicy
project:
  desc: null
  value: icrl
proportional_control_coeff:
  desc: null
  value: 10
proportional_cost_ema_alpha:
  desc: null
  value: 0.5
reset_policy:
  desc: null
  value: false
reward_gae_lambda:
  desc: null
  value: 0.95
reward_gamma:
  desc: null
  value: 0.99
reward_vf_coef:
  desc: null
  value: 0.5
reward_vf_layers:
  desc: null
  value:
  - 64
  - 64
save_dir:
  desc: null
  value: ./icrl/wandb/run-20220609_105900-ga6gkp9g/files
save_every:
  desc: null
  value: 1
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 83
shared_layers:
  desc: null
  value: null
sync_wandb:
  desc: null
  value: false
target_kl:
  desc: null
  value: 0.01
train_env_id:
  desc: null
  value: JTL-v0
train_gail_lambda:
  desc: null
  value: false
update_penalty_after:
  desc: null
  value: 1
use_curiosity_driven_exploration:
  desc: null
  value: false
use_logical_net:
  desc: null
  value: true
use_pid:
  desc: null
  value: false
use_sde:
  desc: null
  value: false
verbose:
  desc: null
  value: 2
wandb_sweep:
  desc: null
  value: false
warmup_timesteps:
  desc: null
  value: null
