wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1656423202
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 19
      4: 3.8.13
      5: 0.12.19
      8:
      - 5
anneal_clr_by_factor:
  desc: null
  value: 1.0
backward_iters:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 64
budget:
  desc: null
  value: 0.0
clip_obs:
  desc: null
  value: 20
clip_range:
  desc: null
  value: 0.2
clip_range_cost_vf:
  desc: null
  value: null
clip_range_reward_vf:
  desc: null
  value: null
cn_acs_select_dim:
  desc: null
  value: null
cn_batch_size:
  desc: null
  value: null
cn_eps:
  desc: null
  value: 1.0e-05
cn_l1_coeff:
  desc: null
  value: 0.0
cn_l2_coeff:
  desc: null
  value: 0.0
cn_layers:
  desc: null
  value:
  - 20
cn_learning_rate:
  desc: null
  value: 0.003
cn_normalize:
  desc: null
  value: false
cn_obs_select_dim:
  desc: null
  value:
  - 5
  - 6
  - 7
  - 8
  - 9
cn_plot_every:
  desc: null
  value: 1
cn_reg_coeff:
  desc: null
  value: 0
cn_target_kl_new_old:
  desc: null
  value: 10
cn_target_kl_old_new:
  desc: null
  value: 10
cn_temp:
  desc: null
  value: 1.0
cn_temp_delta:
  desc: null
  value: 0.0
config_file:
  desc: null
  value: config_icrl_jtl.json
cost_gae_lambda:
  desc: null
  value: 0.95
cost_gamma:
  desc: null
  value: 0.99
cost_info_str:
  desc: null
  value: cost
cost_vf_coef:
  desc: null
  value: 0.5
cost_vf_layers:
  desc: null
  value:
  - 64
  - 64
derivative_control_coeff:
  desc: null
  value: 0
derivative_cost_ema_alpha:
  desc: null
  value: 0.5
deterministic:
  desc: null
  value: false
device:
  desc: null
  value: cpu
dont_normalize_cost:
  desc: null
  value: true
dont_normalize_obs:
  desc: null
  value: true
dont_normalize_reward:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.0
eval_env_id:
  desc: null
  value: CJTL-v0
eval_every:
  desc: null
  value: 2048
expert_path:
  desc: null
  value: icrl/expert_data/JTL
expert_rollouts:
  desc: null
  value: 20
file_to_run:
  desc: null
  value: icrl
forward_timesteps:
  desc: null
  value: 50000
group:
  desc: null
  value: null
integral_control_coeff:
  desc: null
  value: 0.0001
learning_rate:
  desc: null
  value: 0.0003
max_grad_norm:
  desc: null
  value: 0.5
n_epochs:
  desc: null
  value: 10
n_iters:
  desc: null
  value: 200
n_steps:
  desc: null
  value: 2048
name:
  desc: null
  value: JTL-v0_CJTL-v0_dnc_True_dno_True_dnr_True_ws_True_s_83_sid_-1
no_importance_sampling:
  desc: null
  value: false
num_threads:
  desc: null
  value: 5
penalty_initial_value:
  desc: null
  value: 1
penalty_learning_rate:
  desc: null
  value: 0.1
per_step_importance_sampling:
  desc: null
  value: false
pid_delay:
  desc: null
  value: 1
policy_layers:
  desc: null
  value:
  - 64
  - 64
policy_name:
  desc: null
  value: TwoCriticsMlpPolicy
project:
  desc: null
  value: icrl
proportional_control_coeff:
  desc: null
  value: 10
proportional_cost_ema_alpha:
  desc: null
  value: 0.5
reset_policy:
  desc: null
  value: false
reward_gae_lambda:
  desc: null
  value: 0.95
reward_gamma:
  desc: null
  value: 0.99
reward_vf_coef:
  desc: null
  value: 0.5
reward_vf_layers:
  desc: null
  value:
  - 64
  - 64
save_dir:
  desc: null
  value: ./icrl/wandb/run-20220628_133322-3dh0rv0t/files
save_every:
  desc: null
  value: 1
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 83
shared_layers:
  desc: null
  value: null
sync_wandb:
  desc: null
  value: false
target_kl:
  desc: null
  value: 0.01
train_env_id:
  desc: null
  value: JTL-v0
train_gail_lambda:
  desc: null
  value: false
update_penalty_after:
  desc: null
  value: 1
use_curiosity_driven_exploration:
  desc: null
  value: false
use_logical_net:
  desc: null
  value: false
use_pid:
  desc: null
  value: false
use_sde:
  desc: null
  value: false
verbose:
  desc: null
  value: 2
wandb_sweep:
  desc: null
  value: true
warmup_timesteps:
  desc: null
  value: null
